database:
  host: localhost
  port: 5432
  user: postgres
  password: rootpw
  dbname: chronicle
  sslmode: disable

redis:
  host: localhost
  port: 6379
  password:
  db:
  
jwt_secret: ahay
cache_response: true