database:
  host: localhost
  port: 5432
  user: postgres
  password:
  dbname: chronicle-test
  sslmode: disable

jwt_secret: ahay
cache_response: true

redis:
  host: localhost
  port: 6379
  password:
  db: 0